version: '2'

services:
    capnorg-mysql:
        image: mysql:8.0.16
        container_name: database-server
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=takatech
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
networks:
    code-network:
        driver: bridge
